all:
  children:
    dcs:
      hosts:
        consul:
          ansible_host: 192.168.11.100
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
    db:
      hosts:
        pg1:
          ansible_host: 192.168.11.120
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
        pg2:
          ansible_host: 192.168.11.121
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
        pg3:
          ansible_host: 192.168.11.122
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
    proxy:
      hosts:
        haproxy:
          ansible_host: 192.168.11.101
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
